function [data_table] = maxK_table_import_data( ...
    csv_path, ...
    gear_ratio, ...
    tire_radius, ...
    max_voltage, ...
    min_voltage, ...
    st, ...
    data_set_starts, ...
    data_set_stops,)
%maxK_table_import_data Imports .csv for processing
%   Detailed explanation goes here

raw_data = importdata("csv_path");


end