function x = fill_x(X, x, i)
    x.TH_RAW = X(i,2);
    x.ST_RAW = X(i,3);
    x.VB_RAW = X(i,4);
    x.WT_RAW = X(i,5:6);
    x.WM_RAW = X(i,7:8);
    x.GS_RAW = X(i,9);
    x.AV_RAW = X(i,10:12);
    x.IB_RAW = X(i,13);
    x.MT_RAW = X(i,14);
    x.CT_RAW = X(i,15);
    x.IT_RAW = X(i,16);
    x.MC_RAW = X(i,17);
    x.IC_RAW = X(i,18);
    x.BT_RAW = X(i,19);
    x.AG_RAW = X(i,20:22);
    x.TO_RAW = X(i,23:24);
    x.DB_RAW = X(i,25);
    x.PI_RAW = X(i,26);
    x.PP_RAW = X(i,27);
end