%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Inver\OneDrive\Desktop\Book1.xlsx
%    Worksheets: 60V - 340V
%
% Auto-generated by MATLAB on 14-Aug-2022 22:30:59

%% Set up the Import Options and import the data
num_sheets = 29;
opts = spreadsheetImportOptions("NumVariables", 7);
motor_data = zeros(69, 7, 29);

% Specify sheet and range
opts.DataRange = "A2:G70";

% Specify column names and types
opts.VariableNames = ["VoltageV", "CurrentA", "SpeedRPM", "InputPowerW", "OutputPowerW", "TorqueNcm", "Efficiency"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
for i = 1:1:29
    voltage = (i*10) + 50;
    if voltage ~= 200
        opts.Sheet = num2str(voltage) + "V";
        motor_data(:, :, i) = table2array(readtable("C:\Users\Inver\OneDrive\Desktop\Motor_Data_Analysis\all_motor_data.xlsx", opts, "UseExcel", false));
    
        plot(motor_data(:, 3, i), motor_data(:, 6, i))
        hold on

    end
end

%% Clear temporary variables
clear opts