function [fitresult, gof] = createFit(timmy, torquey)
%CREATEFIT(TIMMY,TORQUEY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: timmy
%      Y Output: torquey
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-May-2025 16:56:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( timmy, torquey );
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.9999;
[fitresult, gof] = fit( xData, yData, ft, opts );


