function [fitresult, gof] = createFit1(timmy, overy)
%CREATEFIT1(TIMMY,OVERY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: timmy
%      Y Output: overy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-May-2025 17:47:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( timmy, overy );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.9995;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'overy vs. timmy', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'timmy', 'Interpreter', 'none' );
ylabel( 'overy', 'Interpreter', 'none' );
grid on


